<?php

// Auto-generated by php artisan usim:sync
// Do not edit manually, changes will be overwritten.

return [
  'main' => 
  [
    'display_name' => 'Main Organization',
    'description' => 'Default system unit.',
  ],
];
