<?php

// @usim: feature="core", type="lang"

// Auto-generated by php artisan usim:sync
// Do not edit manually, changes will be overwritten.

return [
  'main' => 
  [
    'display_name' => 'Inicial',
    'description' => 'Unidad base del sistema.',
  ],
  'lobby' => 
  [
    'display_name' => 'Espera',
    'description' => 'Unidad base del sistema.',
  ],
  'idei' => 
  [
    'display_name' => 'Instituto de Informática',
    'description' => 'Instituto de investigación.',
  ],
  'ingeo' => 
  [
    'display_name' => 'Instituto de Geología',
    'description' => 'Instituto de investigación.',
  ],
  'oafa' => 
  [
    'display_name' => 'O.A.F.A.',
    'description' => 'Observatorio Astronómico Félix Aguilar',
  ],
  'comunicación' => 
  [
    'display_name' => 'Comunicación',
    'description' => 'Departamento de comunicación.',
  ],
];
