<?php

// @usim: feature="core", type="lang"

// Auto-generated by php artisan usim:sync
// Do not edit manually, changes will be overwritten.

return [
  'main' => 
  [
    'display_name' => 'Organización Principal',
    'description' => 'Unidad base del sistema.',
  ],
];
