<?php

// @usim: feature="core", type="lang"

// Auto-generated by php artisan usim:sync
// Do not edit manually, changes will be overwritten.

return [
  'main' => 
  [
    'display_name' => 'Initial',
    'description' => 'Default system unit.',
  ],
  'lobby' => 
  [
    'display_name' => 'Lobby',
    'description' => 'Default system unit.',
  ],
  'idei' => 
  [
    'display_name' => 'Institute of Informatics',
    'description' => 'Institute for Idei operations.',
  ],
  'ingeo' => 
  [
    'display_name' => 'Institute of Geology',
    'description' => 'Institute for Ingeo operations.',
  ],
  'oafa' => 
  [
    'display_name' => 'A.O.F.A.',
    'description' => 'Félix Aguilar Astronomical Observatory',
  ],
  'comunicación' => 
  [
    'display_name' => 'Communication',
    'description' => 'Communication department.',
  ],
];
