#!/bin/bash
git fetch --prune

for branch in $(git branch --format='%(refname:short)'); do
    remote_branch=$(git for-each-ref --format='%(upstream:short)' refs/heads/$branch)
    if [ -z "$remote_branch" ]; then
        echo "La rama '$branch' no tiene remoto. Eliminando..."
        git branch -d "$branch"
    fi
done
echo "Limpieza de ramas locales completada."

#TODO: Considerar que la rama local puede estar en otro repositorio remoto, no necesariamente el origin.
# En ese caso, se debería verificar si la rama remota existe en el repositorio remoto correspondiente antes de eliminar la rama local.
