<?php
// @usim: feature="admin", type="service"
namespace App\Services\Units;

use App\Contracts\UnitTranslationGeneratorContract;
use Illuminate\Filesystem\Filesystem;

class UnitTranslationGenerator implements UnitTranslationGeneratorContract
{
    public function __construct(
        protected Filesystem $files
    ) {
    }

    /**
     * @param array<string, array{
     *     type?: string|null,
     *     parent?: string|null,
     *     default_translations?: array<string, mixed>
     * }> $structure
     * @param string $filePrefix
     * @param string|null $baseLangPath
     * @return array<int, string>
     */
    public function generate(array $structure, string $filePrefix = 'unit', ?string $baseLangPath = null): array
    {
        $locales = [];

        foreach ($structure as $slug => $data) {
            if (!isset($data['default_translations'])) {
                continue;
            }

            foreach ($data['default_translations'] as $locale => $translations) {
                if ($locale !== '') {
                    $locales[$locale][$slug] = $translations;
                }
            }
        }

        $generatedFiles = [];
        $basePath = $baseLangPath ?? (function_exists('lang_path') ? lang_path() : resource_path('lang'));

        foreach ($locales as $locale => $keys) {
            $path = "{$basePath}/{$locale}";

            if (!$this->files->isDirectory($path)) {
                $this->files->makeDirectory($path, 0755, true);
            }

            $filePath = "{$path}/{$filePrefix}.php";
            $content = $this->formatPhpArrayContent($keys);

            $this->files->put($filePath, $content);
            $generatedFiles[] = $filePath;
        }

        return $generatedFiles;
    }

    /**
     * @param array<string, mixed> $data
     */
    protected function formatPhpArrayContent(array $data): string
    {
        $export = var_export($data, true);
        $export = (string) preg_replace("/^([ ]*)array \(/m", "$1[", $export);
        $export = (string) preg_replace("/^([ ]*)\)/m", "$1]", $export);
        $export = str_replace("=> \n[", "=> [", $export);

        return "<?php\n\n// Auto-generated by php artisan usim:sync\n// Do not edit manually, changes will be overwritten.\n\nreturn {$export};\n";
    }
}
